version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: mod

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - errorlint
    - wrapcheck
    - ineffassign
    - unused
    - durationcheck
    - contextcheck
    - containedctx
    - noctx
    - fatcontext
    - copyloopvar
    - bodyclose
    - canonicalheader
    - nosprintfhostport
    - sloglint
    - loggercheck
    - spancheck
    - gosec
    - bidichk
    - asciicheck
    - gocyclo
    - dupl
    - revive
    - importas
    - prealloc
    - perfsprint
    - paralleltest
    - tparallel
    - thelper
    - testpackage

  settings:
    gocyclo:
      min-complexity: 20

    importas:
      no-unaliased: false
      no-extra-aliases: false

    sloglint:
      no-mixed-args: true
      kv-only: true
      static-msg: true

    spancheck:
      checks:
        - no-extraneous
        - end-span
        - context-propagation

    # чтобы не заваливать return ctx.Err()
    wrapcheck:
      ignore-sigs:
        - '^context\.Canceled$'
        - '^context\.DeadlineExceeded$'

  # v2: исключения лежат под linters.exclusions
  exclusions:
    generated: strict
    paths:
      - gen
      - web
    rules:
      - path: '_test\.go'
        linters:
          - dupl
          - gocyclo
          - gosec
      - path: 'internal/adapters/inbound/handlers/chat\.go'
        linters:
          - wrapcheck
