version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - gosec
    - gocyclo
    - stylecheck
    - gofmt

linters-settings:
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - gen
    - web
