services:
  redis:
    image: redis:8.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    # image: confluentinc/cp-kafka:latest
    # container_name: kafka
    # ports:
    #   - "9092:9092"
    # environment:
    #   KAFKA_CLUSTER_ID: "mNWf7ow-QOWob6S8hlNbYA"
    #   KAFKA_NODE_ID: 1
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #   KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    #   KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    #   KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
    #   KAFKA_PROCESS_ROLES: "broker,controller"
    # volumes:
    #   - kafka-data:/var/lib/kafka/data
    image: bitnamilegacy/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NODE_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/logs/kafka

volumes:
  redis-data:
  kafka-data:
