app:

http:
  address: "localhost:8000"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  timeout: 5s

kafka:
  address: "127.0.0.1:9092"
  test-topic: "test-topic"
  group-id: "test-group"
  network: "tcp"

retry:
  attempts: 5
  initial: 1s
  max: 15s
  factor: 2.0
  jitter: true
