name: CI

on:
  push: {}
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Keep in sync with Makefile's GOLANGCI_LINT_V
          version: v2.5.0
          args: --timeout 5m

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: make deps

      - name: Formatting check
        run: make fmt-check

      - name: Vet
        run: make vet

      - name: Tests
        run: make test
